version: v1.8.11
pkg: github.com/tqtcloud/workflow-backend
name: workflow-backend
description: 工作流后端
enable_keyauth: false
enable_mysql: false
enable_mongodb: true
gen_example: true
http_framework: go-restful
enable_cache: false
