package impl

type AutoGenerated struct {
	Project struct {
		KeepDependencies string `json:"keepDependencies"`
		Properties       struct {
			ComDabsquaredGitlabjenkinsConnectionGitLabConnectionProperty struct {
				Plugin string `json:"-plugin"`
			} `json:"com.dabsquared.gitlabjenkins.connection.GitLabConnectionProperty"`
			OrgJenkinsciPluginsGitlablogoGitlabLogoProperty struct {
				Plugin string `json:"-plugin"`
			} `json:"org.jenkinsci.plugins.gitlablogo.GitlabLogoProperty"`
			ComSynopsysArcJenkinsciPluginsJobrestrictionsJobsJobRestrictionProperty struct {
				Plugin string `json:"-plugin"`
			} `json:"com.synopsys.arc.jenkinsci.plugins.jobrestrictions.jobs.JobRestrictionProperty"`
			JenkinsModelBuildDiscarderProperty struct {
				Strategy struct {
					Class              string `json:"-class"`
					DaysToKeep         string `json:"daysToKeep"`
					NumToKeep          string `json:"numToKeep"`
					ArtifactDaysToKeep string `json:"artifactDaysToKeep"`
					ArtifactNumToKeep  string `json:"artifactNumToKeep"`
				} `json:"strategy"`
			} `json:"jenkins.model.BuildDiscarderProperty"`
			HudsonModelParametersDefinitionProperty struct {
				ParameterDefinitions struct {
					NetUazniaLukanusHudsonPluginsGitparameterGitParameterDefinition struct {
						Plugin             string `json:"-plugin"`
						Name               string `json:"name"`
						UUID               string `json:"uuid"`
						Type               string `json:"type"`
						Branch             string `json:"branch"`
						TagFilter          string `json:"tagFilter"`
						BranchFilter       string `json:"branchFilter"`
						SortMode           string `json:"sortMode"`
						DefaultValue       string `json:"defaultValue"`
						SelectedValue      string `json:"selectedValue"`
						QuickFilterEnabled string `json:"quickFilterEnabled"`
						ListSize           string `json:"listSize"`
					} `json:"net.uaznia.lukanus.hudson.plugins.gitparameter.GitParameterDefinition"`
					HudsonModelStringParameterDefinition struct {
						Name         string `json:"name"`
						DefaultValue string `json:"defaultValue"`
						Trim         string `json:"trim"`
					} `json:"hudson.model.StringParameterDefinition"`
				} `json:"parameterDefinitions"`
			} `json:"hudson.model.ParametersDefinitionProperty"`
		} `json:"properties"`
		Scm struct {
			Class             string `json:"-class"`
			Plugin            string `json:"-plugin"`
			ConfigVersion     string `json:"configVersion"`
			UserRemoteConfigs struct {
				HudsonPluginsGitUserRemoteConfig struct {
					URL           string `json:"url"`
					CredentialsID string `json:"credentialsId"`
				} `json:"hudson.plugins.git.UserRemoteConfig"`
			} `json:"userRemoteConfigs"`
			Branches struct {
				HudsonPluginsGitBranchSpec struct {
					Name string `json:"name"`
				} `json:"hudson.plugins.git.BranchSpec"`
			} `json:"branches"`
			DoGenerateSubmoduleConfigurations string `json:"doGenerateSubmoduleConfigurations"`
			SubmoduleCfg                      struct {
				Class string `json:"-class"`
			} `json:"submoduleCfg"`
		} `json:"scm"`
		AssignedNode                     string `json:"assignedNode"`
		CanRoam                          string `json:"canRoam"`
		Disabled                         string `json:"disabled"`
		BlockBuildWhenDownstreamBuilding string `json:"blockBuildWhenDownstreamBuilding"`
		BlockBuildWhenUpstreamBuilding   string `json:"blockBuildWhenUpstreamBuilding"`
		Jdk                              string `json:"jdk"`
		ConcurrentBuild                  string `json:"concurrentBuild"`
		Builders                         struct {
			HudsonTasksShell []struct {
				Command string `json:"command"`
			} `json:"hudson.tasks.Shell"`
		} `json:"builders"`
		Publishers struct {
			JenkinsPluginsPublishOverSSHBapSSHPublisherPlugin struct {
				Plugin        string `json:"-plugin"`
				ConsolePrefix string `json:"consolePrefix"`
				Delegate      struct {
					Plugin     string `json:"-plugin"`
					Publishers struct {
						JenkinsPluginsPublishOverSSHBapSSHPublisher struct {
							Plugin     string `json:"-plugin"`
							ConfigName string `json:"configName"`
							Verbose    string `json:"verbose"`
							Transfers  struct {
								JenkinsPluginsPublishOverSSHBapSSHTransfer struct {
									SourceFiles        string `json:"sourceFiles"`
									RemoteDirectorySDF string `json:"remoteDirectorySDF"`
									Flatten            string `json:"flatten"`
									CleanRemote        string `json:"cleanRemote"`
									NoDefaultExcludes  string `json:"noDefaultExcludes"`
									MakeEmptyDirs      string `json:"makeEmptyDirs"`
									PatternSeparator   string `json:"patternSeparator"`
									ExecCommand        string `json:"execCommand"`
									ExecTimeout        string `json:"execTimeout"`
									UsePty             string `json:"usePty"`
									UseAgentForwarding string `json:"useAgentForwarding"`
								} `json:"jenkins.plugins.publish__over__ssh.BapSshTransfer"`
							} `json:"transfers"`
							UseWorkspaceInPromotion string `json:"useWorkspaceInPromotion"`
							UsePromotionTimestamp   string `json:"usePromotionTimestamp"`
						} `json:"jenkins.plugins.publish__over__ssh.BapSshPublisher"`
					} `json:"publishers"`
					ContinueOnError         string `json:"continueOnError"`
					FailOnError             string `json:"failOnError"`
					AlwaysPublishFromMaster string `json:"alwaysPublishFromMaster"`
					HostConfigurationAccess struct {
						Class     string `json:"-class"`
						Reference string `json:"-reference"`
					} `json:"hostConfigurationAccess"`
				} `json:"delegate"`
			} `json:"jenkins.plugins.publish__over__ssh.BapSshPublisherPlugin"`
		} `json:"publishers"`
		BuildWrappers struct {
			HudsonPluginsTimestamperTimestamperBuildWrapper struct {
				Plugin string `json:"-plugin"`
			} `json:"hudson.plugins.timestamper.TimestamperBuildWrapper"`
			JenkinsPluginsNodejsNodeJSBuildWrapper struct {
				Plugin                 string `json:"-plugin"`
				NodeJSInstallationName string `json:"nodeJSInstallationName"`
				CacheLocationStrategy  struct {
					Class string `json:"-class"`
				} `json:"cacheLocationStrategy"`
			} `json:"jenkins.plugins.nodejs.NodeJSBuildWrapper"`
		} `json:"buildWrappers"`
	} `json:"project"`
}

//var metexml =`
//<project>
//<actions/>
//<description/>
//<keepDependencies>false</keepDependencies>
//<properties>
//<com.dabsquared.gitlabjenkins.connection.GitLabConnectionProperty plugin="gitlab-plugin@1.5.12">
//<gitLabConnection/>
//</com.dabsquared.gitlabjenkins.connection.GitLabConnectionProperty>
//<org.jenkinsci.plugins.gitlablogo.GitlabLogoProperty plugin="gitlab-logo@1.0.3">
//<repositoryName/>
//</org.jenkinsci.plugins.gitlablogo.GitlabLogoProperty>
//<com.synopsys.arc.jenkinsci.plugins.jobrestrictions.jobs.JobRestrictionProperty plugin="job-restrictions@0.8"/>
//<jenkins.model.BuildDiscarderProperty>
//<strategy class="hudson.tasks.LogRotator">
//<daysToKeep>-1</daysToKeep>
//<numToKeep>4</numToKeep>
//<artifactDaysToKeep>-1</artifactDaysToKeep>
//<artifactNumToKeep>-1</artifactNumToKeep>
//</strategy>
//</jenkins.model.BuildDiscarderProperty>
//<hudson.model.ParametersDefinitionProperty>
//<parameterDefinitions>
//<net.uaznia.lukanus.hudson.plugins.gitparameter.GitParameterDefinition plugin="git-parameter@0.9.11">
//<name>branch</name>
//<description/>
//<uuid>c99fff32-d399-4022-a9c8-4a08cab81e5a</uuid>
//<type>PT_BRANCH</type>
//<branch>sit</branch>
//<tagFilter>*</tagFilter>
//<branchFilter>.*sit.*</branchFilter>
//<sortMode>DESCENDING_SMART</sortMode>
//<defaultValue>origin/sit</defaultValue>
//<selectedValue>DEFAULT</selectedValue>
//<quickFilterEnabled>true</quickFilterEnabled>
//<listSize>20</listSize>
//</net.uaznia.lukanus.hudson.plugins.gitparameter.GitParameterDefinition>
//<hudson.model.StringParameterDefinition>
//<name>CODE_MODULE</name>
//<description/>
//<defaultValue>ad_admin</defaultValue>
//<trim>false</trim>
//</hudson.model.StringParameterDefinition>
//</parameterDefinitions>
//</hudson.model.ParametersDefinitionProperty>
//</properties>
//<scm class="hudson.plugins.git.GitSCM" plugin="git@4.2.2">
//<configVersion>2</configVersion>
//<userRemoteConfigs>
//<hudson.plugins.git.UserRemoteConfig>`
//
////`<url>https://gitlab.leyaoyao.com/front-end/project.git</url>`
//
//
//var xml2 = `<credentialsId>4a2d7ab1-1fac-4788-833e-ff1b8b53d665</credentialsId>
//</hudson.plugins.git.UserRemoteConfig>
//</userRemoteConfigs>
//<branches>
//<hudson.plugins.git.BranchSpec>`
//
////<name>$branch</name>
//
//
//var xml3 = `</hudson.plugins.git.BranchSpec>
//</branches>
//<doGenerateSubmoduleConfigurations>false</doGenerateSubmoduleConfigurations>
//<submoduleCfg class="list"/>
//<extensions/>
//</scm>
//<assignedNode>Jenkins_Slave_192.168.101.71</assignedNode>
//<canRoam>false</canRoam>
//<disabled>false</disabled>
//<blockBuildWhenDownstreamBuilding>false</blockBuildWhenDownstreamBuilding>
//<blockBuildWhenUpstreamBuilding>false</blockBuildWhenUpstreamBuilding>
//<jdk>(System)</jdk>
//<triggers/>
//<concurrentBuild>false</concurrentBuild>
//<builders>`
//
//var xml4shell = `<hudson.tasks.Shell>
//<command>cd $CODE_MODULE rm -rf dist npm install --save-dev npm run-script build zip -r dist.zip dist</command>
//</hudson.tasks.Shell>
//<hudson.tasks.Shell>
//<command>cp -r $CODE_MODULE/dist.zip .</command>
//</hudson.tasks.Shell>`
//
//
//</builders>
//<publishers>
//<jenkins.plugins.publish__over__ssh.BapSshPublisherPlugin plugin="publish-over-ssh@1.20.1">
//<consolePrefix>SSH: </consolePrefix>
//<delegate plugin="publish-over@0.22">
//<publishers>
//<jenkins.plugins.publish__over__ssh.BapSshPublisher plugin="publish-over-ssh@1.20.1">
//<configName>192.168.101.6_Nginx</configName>
//<verbose>false</verbose>
//<transfers>
//<jenkins.plugins.publish__over__ssh.BapSshTransfer>
//<remoteDirectory/>
//<sourceFiles>dist.zip</sourceFiles>
//<excludes/>
//<removePrefix/>
//<remoteDirectorySDF>false</remoteDirectorySDF>
//<flatten>false</flatten>
//<cleanRemote>false</cleanRemote>
//<noDefaultExcludes>false</noDefaultExcludes>
//<makeEmptyDirs>false</makeEmptyDirs>
//<patternSeparator>[, ]+</patternSeparator>
//<execCommand>unzip dist.zip yes | cp -r dist/* /usr/local/nginx/sit/advert/ rm -rf dist*</execCommand>
//<execTimeout>120000</execTimeout>
//<usePty>false</usePty>
//<useAgentForwarding>false</useAgentForwarding>
//</jenkins.plugins.publish__over__ssh.BapSshTransfer>
//</transfers>
//<useWorkspaceInPromotion>false</useWorkspaceInPromotion>
//<usePromotionTimestamp>false</usePromotionTimestamp>
//</jenkins.plugins.publish__over__ssh.BapSshPublisher>
//</publishers>
//<continueOnError>false</continueOnError>
//<failOnError>false</failOnError>
//<alwaysPublishFromMaster>false</alwaysPublishFromMaster>
//<hostConfigurationAccess class="jenkins.plugins.publish_over_ssh.BapSshPublisherPlugin" reference="../.."/>
//</delegate>
//</jenkins.plugins.publish__over__ssh.BapSshPublisherPlugin>
//</publishers>
//<buildWrappers>
//<hudson.plugins.timestamper.TimestamperBuildWrapper plugin="timestamper@1.10"/>
//<jenkins.plugins.nodejs.NodeJSBuildWrapper plugin="nodejs@1.3.3">
//<nodeJSInstallationName>NodeJS10.6.2</nodeJSInstallationName>
//<cacheLocationStrategy class="jenkins.plugins.nodejs.cache.DefaultCacheLocationLocator"/>
//</jenkins.plugins.nodejs.NodeJSBuildWrapper>
//</buildWrappers>
//</project>
